### ISSUE TITLE
Incompatibility with changing text color/color gradient at runtime

### ISSUE THREAD

**Issue by vcesario** [mdechatech/CharTweener#3]
Calling `DOFade()` for the second time after changing a TMP_Text's color properties (be it `color` or `vertexGradient`) will reset it to its former solid color. Is this a known behavior that needs to be locally adressed or I'm just missing something?

**Comment by zephyo** [comment]
Figured it out.

In CharTweener.cs CreateProxyColor, change to:

```
            var color = new CharColor
            {
                VertexGradient = Text.colorGradient,
                Color = Text.color,
            };

```
Previously:
```
            var color = new CharColor
            {
                Color = Text.color,
                VertexGradient = Text.colorGradient
            };
```

The order matters, because when we set Color, we really call SetColor(), which doesn't do anything if VertexGradient isn't set first.

**Comment by alexpdaniel** [comment]
Thanks for that Zephyo. In my first use of this library I didn't have this issue, then on the next my text would flash back to the originally set color before doing the tween. Your solution fixed that issue for me, so thanks!
